spring:

  # 데이터베이스
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '0000'
    url: jdbc:mysql://localhost:13306/saphy
  jpa:
    show-sql: 'false'
    hibernate:
      ddl-auto: create
    open-in-view: 'false'
    database-platform: org.hibernate.dialect.MySQLDialect

  # JWT 설정 추가
  jwt:
    secret-key: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
    token-validity: 3600000 # 1시간

# p6spy log
decorator:
  datasource:
    p6spy:
      enable-logging: 'true'

# logging
logging:
  level:
    org:
      springframework:
        core:
          LocalVariableTableParameterNameDiscoverer: error
      hibernate:
        sql: debug
    p6spy: info
