spring:

  # Database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '00000000'
    url: jdbc:mysql://saphy-server.cv4c6ysy8cvy.ap-northeast-2.rds.amazonaws.com:3306/saphy

  # Spring Data JPA
  jpa:
    show-sql: 'false'
    hibernate:
      ddl-auto: create
    open-in-view: 'false'
    database-platform: org.hibernate.dialect.MySQLDialect

# p6spy log
decorator:
  datasource:
    p6spy:
      enable-logging: 'true'

# logging
logging:
  level:
    org:
      springframework:
        core:
          LocalVariableTableParameterNameDiscoverer: error
      hibernate:
        sql: debug
    p6spy: info
